from os.path import expanduser


# Constants
HOME=expanduser("~")
SITECONF='site.conf'
CONFROOT='root'
CONTENTDIR='content'
DIRDEFAULTFILE='index'
TARGETDIR='site'
ASSETDIR='assets'
THEMEDIR='themes'
SITEMAPFILE='sitemap.xml'
SITEMAPTXTFILE='sitemap.txt'
HOOKDIR='hooks'
DEFAULTPAGETEMPLATE='pages.mako'
TEMPLATEDIR='templates'
NEWLINE='\n'
DATEFORMAT='%Y-%m-%d'
RSSFEEDFILE='feed.rss'
HEADERPROFILEDIR='header_profiles'
STOPWORDSFILE='stopwords.txt'
SEARCHINDEXFILE='search-index.json'
SEARCHMODEJSFILE='pagegen-reload-on-regenerate.js'
SEARCHMODESITEUPDATEDFILE='pagegen_site_hash'
DIRECTORIESTEMPLATE='directories.mako'
TAGSTEMPLATE='tags.mako'
TAGTEMPLATE='tag.mako'
AUTHORTEMPLATE='author.mako'
AUTHORSTEMPLATE='authors.mako'
SHORTCODECUSTOM='shortcodes'
AUTHORSCONF='authors.conf'
