.TH PAGEGEN 1 "" "2.0.0"
.\" ===================================================
.SH NAME
pagegen \(em static web site generator
.\" ===================================================
.SH SYNOPSIS
.B pagegen
[init]
.\" ===================================================
.SH OPTIONS
.\" ---------------------------------------------------
.TP
.B No arguments
Generate a site from current directory if it contains site.conf, or first of the current directory parents containing the configuration file. 
.\" ---------------------------------------------------
.TP
.B init
Setup the required directories and files for a new site in current (must be empty) directory. Does not perform generation.
.SH DESCRIPTION
A static web site generator processes input and produces regular web site files, such as .html, .css, .js etc. Pagegen uses flat text files and directories to order and store it's input. When a site is generated Pagegen processes the input adding site menues, headers and footers etc all ready to be uploaded to a web server.

Please see http://pagegen.phnd.net for complete documentation.
