.TH PAGEGEN 1 "" "2.0.0"
.\" ===================================================
.SH NAME
pagegen \(em static web site generator
.\" ===================================================
.SH SYNOPSIS
.B pagegen
[-i|--init] [-g|--generate] [-c|--config <file>] [-p|--pagegen-config <file>] [-v|--version]
.\" ===================================================
.SH OPTIONS
.\" ---------------------------------------------------
.TP
.B -i|--init
Setup the required directories and files for a new site in current (must be empty) directory. Does not perform generation.
.\" ---------------------------------------------------
.TP
.B -g|--generate
Generate html and place in site directory
.\" ---------------------------------------------------
.TP
.B -c|--config <file>
Specify site config file(site.conf)
.\" ---------------------------------------------------
.TP
.B -p|--pagegen-config <file>
Specify pagegen config file(pagegen.conf)
.\" ---------------------------------------------------
.TP
.B -v|--version
Print Pagegen version
.SH DESCRIPTION
A static web site generator processes input and produces regular web site files, such as .html, .css, .js etc. Pagegen uses flat text files and directories to order and store it's input. When a site is generated Pagegen processes the input adding site menues, headers and footers etc all ready to be uploaded to a web server.

Please see http://pagegen.phnd.net for complete documentation.
