#!/bin/bash

# Make executable to run at generation
#
# Available environment variables:
# PAGEGEN_SITE_DIR - Root Pagegen directory
# PAGEGEN_SOURCE_DIR - content directory
# PAGEGEN_TARGET_DIR - site/<environment> directory
# PAGEGEN_BASE_URL - Base url setting
# PAGEGEN_HOOK - Hook name
# PAGEGEN_PAGE_TITLE - Page title
# PAGEGEN_PAGE_URL - Page URL
# PAGEGEN_PAGE_SOURCE_PATH - Page source (content/<page path>
# PAGEGEN_PAGE_TARGET_PATH - Page target (site/<environment>/<page url path>)

echo "$PAGEGEN_HOOK $PAGEGEN_ENVIRONMENT"