#!/bin/bash

# Make executable to run at generation
#
# Available environment variables:
# PAGEGEN_SITE_DIR
# PAGEGEN_SOURCE_DIR
# PAGEGEN_TARGET_DIR
# PAGEGEN_PAGE_TITLE
# PAGEGEN_PAGE_URL
# PAGEGEN_PAGE_SOURCE_PATH
# PAGEGEN_PAGE_TARGET_PATH

echo "Pre generate page"